# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxBh5_IeC9zPQj_vJBFMw4US-lxcJdFt
"""
"""
# main.py
from flask import Flask, request, jsonify
from app.pipeline import health_assistant_pipeline

app = Flask(__name__)

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json
    user_input = data.get("text", "")

    if not user_input:
        return jsonify({"error": "No input text provided"}), 400

    result = health_assistant_pipeline(user_input)
    return jsonify(result)

if __name__ == "__main__":
    app.run(debug=True)
"""

# main.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from app.pipeline import health_assistant_pipeline

app = Flask(__name__)
CORS(app)  # allow frontend requests

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json
    user_input = data.get("text", "")

    if not user_input:
        return jsonify({"error": "No input text provided"}), 400

    result = health_assistant_pipeline(user_input)
    return jsonify(result)

if __name__ == "__main__":
    app.run(debug=True, port=5000)
