# -*- coding: utf-8 -*-
"""medicine_module.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyzhzhaqXbyvmIsAYG6fVbcAIVmAaLnu
"""

import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.feature_extraction.text import CountVectorizer

# ----------------------------
# 1️⃣ Load dataset
# ----------------------------
data = pd.read_csv("disease_medicine.csv")
data = data.fillna("")

# Normalize disease names to lowercase for matching
data["Disease"] = data["Disease"].str.lower()

# ----------------------------
# 2️⃣ Combine medicines for each disease
# ----------------------------
data["All_Meds"] = data.iloc[:, 1:].apply(lambda row: " ".join(row.values.astype(str)), axis=1)

# ----------------------------
# 3️⃣ Encode medicine info using bag-of-words
# ----------------------------
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["All_Meds"])

# Train Nearest Neighbors model
model = NearestNeighbors(n_neighbors=1, metric="cosine")
model.fit(X)

# ----------------------------
# 4️⃣ Function to get medicines for a disease
# ----------------------------
def get_medicines(disease_name):
    disease_name = disease_name.lower().strip()

    if disease_name not in data["Disease"].values:
        print("⚠️ Disease not found exactly — showing closest match:")
        disease_vector = vectorizer.transform([disease_name])
        distances, indices = model.kneighbors(disease_vector)
        idx = indices[0][0]
        matched_disease = data.loc[idx, "Disease"].title()
    else:
        idx = data.index[data["Disease"] == disease_name][0]
        matched_disease = data.loc[idx, "Disease"].title()

    meds = data.loc[idx, ["Med1", "Med2", "Med3", "Med4", "Med5", "Med6"]].tolist()
    return matched_disease, meds

# ----------------------------
# 5️⃣ Example usage
# ----------------------------
if __name__ == "__main__":
    disease = input("Enter disease name: ")
    name, meds = get_medicines(disease)
    print(f"\n💊 Recommended medicines for {name}:")
    for m in meds:
        if m.strip():
            print(" -", m)

import joblib
import os

# Your specified directory
MODEL_DIR = "/content/drive/MyDrive/Mini project/meds_model"
os.makedirs(MODEL_DIR, exist_ok=True)

# Save model, vectorizer, and dataset
joblib.dump(model, os.path.join(MODEL_DIR, "knn_model.pkl"))
joblib.dump(vectorizer, os.path.join(MODEL_DIR, "vectorizer.pkl"))
data.to_csv(os.path.join(MODEL_DIR, "disease_medicine.csv"), index=False)

print(f"✅ Model and data saved successfully to {MODEL_DIR}")

!ls "/content/drive/MyDrive/Mini project/meds_model"

import os

folder = "/content/drive/MyDrive/Mini project/meds_model"
print(os.listdir(folder))

