# -*- coding: utf-8 -*-
"""pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OuV3816oRMNGQWypdnb30TPFX4sUbDI5
"""

# app/pipeline.py
from app.translate_module import detect_and_translate
from app.symptom_extraction_module import extract_symptoms
from app.disease_module import predict_disease
from app.medicine_module import recommend_meds

def health_assistant_pipeline(user_input):
    # Step 1: Translate to English if not English
    english_text = detect_and_translate(user_input)

    # Step 2: Extract symptoms using BioBERT
    symptoms = extract_symptoms(english_text)

    # Step 3: Predict disease
    predicted_disease = predict_disease(symptoms)

    # Step 4: Get medicine recommendations
    medicines = recommend_meds(predicted_disease)

    # Step 5: (Optional) Translate back to user’s language
    final_output = detect_and_translate(medicines)

    return {
        "language": "auto-detected",
        "symptoms": symptoms,
        "predicted_disease": predicted_disease,
        "medicines": medicines,
        "translated_output": final_output
    }

