# -*- coding: utf-8 -*-
"""translate_module.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aa2wO8LDGzrB1zTdzq4E8X-b7BBHrbq5
"""

#!pip install langdetect pandas scikit-learn

from langdetect import detect
from transformers import MarianMTModel, MarianTokenizer

# Mapping language code → Marian model name
MODEL_MAP = {
    "hi": "Helsinki-NLP/opus-mt-hi-en",  # Hindi → English
    "mr": "Helsinki-NLP/opus-mt-mr-en",  # Marathi → English
    "gu": "Helsinki-NLP/opus-mt-gu-en",  # Gujarati → English
    "bn": "Helsinki-NLP/opus-mt-bn-en"   # Bengali → English
}

class MultilingualTranslator:
    def __init__(self, lang_code):
        if lang_code not in MODEL_MAP:
            raise ValueError(f"No model available for language: {lang_code}")
        model_name = MODEL_MAP[lang_code]
        self.tokenizer = MarianTokenizer.from_pretrained(model_name)
        self.model = MarianMTModel.from_pretrained(model_name)

    def translate(self, text):
        inputs = self.tokenizer(text, return_tensors="pt", padding=True)
        translated_tokens = self.model.generate(**inputs)
        return self.tokenizer.decode(translated_tokens[0], skip_special_tokens=True)

def detect_and_translate(text):
    lang_code = detect(text)
    if lang_code != "en" and lang_code in MODEL_MAP:
        translator = MultilingualTranslator(lang_code)
        return translator.translate(text)
    return text  # already in English

detect_and_translate("शरीर में दर्द")
