# -*- coding: utf-8 -*-
"""symptom_extraction_module.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmqmv0xK1agepu7_W72s4d4jZclCLroD
"""

#!pip install transformers datasets seqeval accelerate -q

#!pip uninstall -y transformers

#!pip install transformers==4.57.1

import transformers
import os
import torch
import numpy as np
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)
from seqeval.metrics import classification_report



# -------------------------------
# 1. Load BIO file dynamically
# -------------------------------
def load_bio_file(file_path):
    tokens, labels = [], []
    words, tags = [], []
    label_set = set()  # collect unique labels

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:  # skip blank lines
                if words:
                    tokens.append(words)
                    labels.append(tags)
                    words, tags = [], []
                continue

            try:
                # Some BIO datasets are tab-separated, some space-separated
                parts = line.split()
                if len(parts) != 2:
                    continue
                word, tag = parts
                words.append(word)
                tags.append(tag)
                label_set.add(tag)

                # Sentence boundary if punctuation
                if word.endswith(('.', '!', '?')):
                    tokens.append(words)
                    labels.append(tags)
                    words, tags = [], []
            except:
                continue

    # Catch leftover words if file doesn’t end with punctuation
    if words:
        tokens.append(words)
        labels.append(tags)

    # Build label mappings dynamically
    label_list = sorted(list(label_set))
    label2id = {label: i for i, label in enumerate(label_list)}
    id2label = {i: label for label, i in label2id.items()}

    # Convert tags to ids
    encoded_labels = [[label2id[tag] for tag in seq] for seq in labels]

    dataset = Dataset.from_dict({"tokens": tokens, "labels": encoded_labels})
    return dataset, label2id, id2label

BASE_DIR = os.path.dirname(__file__)   # folder: sehat-connect-app/app/
BIO_FILE_PATH = os.path.join(BASE_DIR, "sample_bio_cleaned.txt")

dataset, label2id, id2label = load_bio_file(BIO_FILE_PATH)
print(transformers.__version__)
# Example usage
dataset, label2id, id2label = load_bio_file("app/sample_bio_cleaned.txt")

print("Sample:", dataset[0])
print("Label2id mapping:", label2id)

# -------------------------------
# 2. Tokenization
# -------------------------------
model_checkpoint = "dmis-lab/biobert-base-cased-v1.1"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        is_split_into_words=True,
        truncation=True,
        padding="max_length",
        max_length=128
    )

    all_labels = []
    for i, labels in enumerate(examples["labels"]):  # labels is a list of lists
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(labels[word_idx])  # first subword gets label
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        all_labels.append(label_ids)

    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs


tokenized_dataset = dataset.map(tokenize_and_align_labels, batched=True)

id2label = {
    0: "B-ADR",
    1: "B-Disease",
    2: "B-Drug",
    3: "B-Finding",
    4: "B-Symptom",
    5: "I-ADR",
    6: "I-Disease",
    7: "I-Drug",
    8: "I-Finding",
    9: "I-Symptom",
    10: "O"
}
label2id = {v: k for k, v in id2label.items()}

# -------------------------------
# 3. Model
# -------------------------------
model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(id2label),
    id2label=id2label,
    label2id=label2id
)

# -------------------------------
# 4. Training Setup
# -------------------------------
import os
os.environ["WANDB_DISABLED"] = "true"

training_args = TrainingArguments(
    output_dir="./results",
    save_steps=500,
    logging_steps=100,
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True,
    report_to=None
)

data_collator = DataCollatorForTokenClassification(tokenizer)

# Split dataset manually
split = tokenized_dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = split["train"]
eval_dataset = split["test"]

# -------------------------------
# 5. Compute metrics
# -------------------------------
def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_labels = [
        [id2label[l] for l in label if l != -100]
        for label in labels
    ]
    true_predictions = [
        [id2label[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    report = classification_report(true_labels, true_predictions, output_dict=True)
    return {"f1": report["micro avg"]["f1-score"]}

# -------------------------------
# 6. Trainer
# -------------------------------
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)


# -------------------------------
# 7. Train & Save
# -------------------------------
trainer.train()
trainer.save_model("biobert_ner_model")

# -------------------------------
# 8. Inference
# -------------------------------
from transformers import pipeline

tokenizer = AutoTokenizer.from_pretrained("biobert_ner_model", truncation=True, model_max_length=256)
model = AutoModelForTokenClassification.from_pretrained("biobert_ner_model")

ner_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",
    device=0
)

text = "After taking the medication, I experienced severe headaches and nausea, followed by dizziness and blurred vision for several hours."
results = ner_pipeline(text)
print(results)

merged_results = []
current = ""

for item in results:
    word = item['word']
    if word.startswith("##"):
        current += word[2:]  # merge subword
    else:
        if current:
            merged_results.append(current)
        current = word
if current:
    merged_results.append(current)

print("Detected symptoms:", merged_results)

# #!zip -r biobert_ner_model.zip biobert_ner_model/

# from google.colab import drive
# drive.mount('/content/drive')

# save_path = "/content/drive/MyDrive/Mini project/biobert_ner_model"

# model.save_pretrained(save_path)
# tokenizer.save_pretrained(save_path)

# from transformers import TrainingArguments
# print(TrainingArguments.__module__)
# print(TrainingArguments.__file__ if hasattr(TrainingArguments, "__file__") else "No file attribute")

