// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwsfjkaylxykyxaynsgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3c2Zqa2F5bHh5a3l4YXluc2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyOTMwNTEsImV4cCI6MjA3NTg2OTA1MX0.Hnkdx0hLF-E6eNUjIqNTZdONgraryCqMJhlRToyV308";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});